### ISSUE TITLE
Site crashed when I tried to join the latest tournament

### ISSUE THREAD

**Issue by jthemphill** [bakert/tournament#3]
I tried to join and the site gave a 5xx error. German tried to manually add me to pod 153 and the site wouldn't let him. We abandoned the app and played games manually.

**Comment by bakert** [comment]
Thanks Jeff.

Error log says:

[Wed Aug 17 01:20:11.397061 2016] [:error] [pid 25569] [client 70.213.8.102:13143] PHP Fatal error:  Uncaught exception 'DatabaseException' with message 'Database failure: 'INSERT INTO player_event (event_id, player_id, name, url, dropped) VALUES ('98', '10206819780629227', 'Jeffrey Hemphill', 'https://www.facebook.com/app_scoped_user_id/10206819780629227/', FALSE)'' in /srv/tournament/src/classes/db.php:19\nStack trace:\n#0 /srv/tournament/src/classes/events.php(11): Db->execute('INSERT INTO pla...')\n#1 /srv/tournament/src/www/addplayer/index.php(39): Events->si
gnUp('98', '102068197806292...', 'Jeffrey Hemphil...', 'https://www.fac...')\n#2 /srv/tournament/src/www/addplayer/index.php(11): AddPlayer->addPlayerToPod('a:3:{i:0;s:17:"...', 'a:2:{i:0;s:2:"9...')\n#3 /srv/tournament/src/www/addplayer/index.php(70): AddPlayer->main()\n#4 {main}\n  thrown in /srv/tournament/src/classes/db.php on line 19, referer: http://mtg.bluebones.net/addplayer/
[Wed Aug 17 01:20:57.011727 2016] [:error] [pid 25539] [client 70.213.8.102:13134] PHP Fatal error:  Uncaught exception 'DatabaseException' with message 'Database failure: 'INSERT INTO player_event (event_id, player_id, name, url, dropped) VALUES ('98', '10206819780629227', 'Jeffrey Hemphill', 'https://www.facebook.com/app_scoped_user_id/10206819780629227/', FALSE)'' in /srv/tournament/src/classes/db.php:19\nStack trace:\n#0 /srv/tournament/src/classes/events.php(11): Db->execute('INSERT INTO pla...')\n#1 /srv/tournament/src/www/addplayer/index.php(39): Events->signUp('98', '102068197806292...', 'Jeffrey Hemphil...', 'https://www.fac...')\n#2 /srv/tournament/src/www/addplayer/index.php(11): AddPlayer->addPlayerToPod('a:3:{i:0;s:17:"...', 'a:2:{i:0;s:2:"9...')\n#3 /srv/tournament/src/www/addplayer/index.php(70): AddPlayer->main()\n#4 {main}\n  thrown in /srv/tournament/src/classes/db.php on line 19, referer: http://mtg.bluebones.net/addplayer/
[Wed Aug 17 01:21:53.825017 2016] [:error] [pid 25571] [client 199.201.64.129:40360] PHP Fatal error:  Uncaught exception 'DatabaseException' with message 'Database failure: 'INSERT INTO player_event (event_id, player_id, name, url, dropped) VALUES ('98', '10206819780629227', 'Jeffrey Hemphill', 'https://www.facebook.com/app_scoped_user_id/10206819780629227/', FALSE)'' in /srv/tournament/src/classes/db.php:19\nStack trace:\n#0 /srv/tournament/src/classes/events.php(11): Db->execute('INSERT INTO pla...')\n#1 /srv/tournament/src/www/addplayer/index.php(39): Events->signUp('98', '102068197806292...', 'Jeffrey Hemphil...', 'https://www.fac...')\n#2 /srv/tournament/src/www/addplayer/index.php(11): AddPlayer->addPlayerToPod('a:3:{i:0;s:17:"...', 'a:2:{i:0;s:2:"9...')\n#3 /srv/tournament/src/www/addplayer/index.php(70): AddPlayer->main()\n#4 {main}\n  thrown in /srv/tournament/src/classes/db.php on line 19, referer: http://mtg.bluebones.net/addplayer/
[Wed Aug 17 01:25:13.001367 2016] [:error] [pid 25570] [client 199.201.64.131:40388] PHP Fatal error:  Uncaught exception 'DatabaseException' with message 'Database failure: 'INSERT INTO player_event (event_id, player_id, name, url, dropped) VALUES ('98', '10206819780629227', 'Jeffrey Hemphill', 'https://www.facebook.com/app_scoped_user_id/10206819780629227/', FALSE)'' in /srv/tournament/src/classes/db.php:19\nStack trace:\n#0 /srv/tournament/src/classes/events.php(11): Db->execute('INSERT INTO pla...')\n#1 /srv/tournament/src/www/addplayer/index.php(39): Events->signUp('98', '102068197806292...', 'Jeffrey Hemphil...', 'https://www.fac...')\n#2 /srv/tournament/src/www/addplayer/index.php(11): AddPlayer->addPlayerToPod('a:3:{i:0;s:17:"...', 'a:2:{i:0;s:2:"9...')\n#3 /srv/tournament/src/www/addplayer/index.php(70): AddPlayer->main()\n#4 {main}\n  thrown in /srv/tournament/src/classes/db.php on line 19, referer: http://mtg.bluebones.net/addplayer/
[Wed Aug 17 02:49:26.784273 2016] [:error] [pid 27086] [client 199.201.64.134:29270] PHP Notice:  Undefined offset: 9 in /srv/tournament/src/classes/pairings.php on line 88, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 02:49:26.784319 2016] [:error] [pid 27086] [client 199.201.64.134:29270] PHP Stack trace:, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 02:49:26.784330 2016] [:error] [pid 27086] [client 199.201.64.134:29270] PHP   1. {main}() /srv/tournament/src/www/report/index.php:0, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 02:49:26.784337 2016] [:error] [pid 27086] [client 199.201.64.134:29270] PHP   2. Report->main() /srv/tournament/src/www/report/index.php:28, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 02:49:26.784343 2016] [:error] [pid 27086] [client 199.201.64.134:29270] PHP   3. Pod->pair() /srv/tournament/src/www/report/index.php:22, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 02:49:26.784348 2016] [:error] [pid 27086] [client 199.201.64.134:29270] PHP   4. Pairings->pair() /srv/tournament/src/classes/pod.php:120, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 02:49:26.784354 2016] [:error] [pid 27086] [client 199.201.64.134:29270] PHP   5. Pairings->getPairingOrdering() /srv/tournament/src/classes/pairings.php:17, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 02:49:26.784359 2016] [:error] [pid 27086] [client 199.201.64.134:29270] PHP   6. Pairings->scorePairings() /srv/tournament/src/classes/pairings.php:44, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 03:34:02.351118 2016] [:error] [pid 27749] [client 70.213.8.102:13145] PHP Notice:  Undefined offset: 9 in /srv/tournament/src/classes/pairings.php on line 88, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 03:34:02.351211 2016] [:error] [pid 27749] [client 70.213.8.102:13145] PHP Stack trace:, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 03:34:02.351228 2016] [:error] [pid 27749] [client 70.213.8.102:13145] PHP   1. {main}() /srv/tournament/src/www/report/index.php:0, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 03:34:02.351242 2016] [:error] [pid 27749] [client 70.213.8.102:13145] PHP   2. Report->main() /srv/tournament/src/www/report/index.php:28, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 03:34:02.351251 2016] [:error] [pid 27749] [client 70.213.8.102:13145] PHP   3. Pod->pair() /srv/tournament/src/www/report/index.php:22, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 03:34:02.351260 2016] [:error] [pid 27749] [client 70.213.8.102:13145] PHP   4. Pairings->pair() /srv/tournament/src/classes/pod.php:120, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 03:34:02.351270 2016] [:error] [pid 27749] [client 70.213.8.102:13145] PHP   5. Pairings->getPairingOrdering() /srv/tournament/src/classes/pairings.php:17, referer: http://mtg.bluebones.net/pod/?pod_id=152
[Wed Aug 17 03:34:02.351278 2016] [:error] [pid 27749] [client 70.213.8.102:13145] PHP   6. Pairings->scorePairings() /srv/tournament/src/classes/pairings.php:44, referer: http://mtg.bluebones.net/pod/?pod_id=152

**Comment by bakert** [comment]
Database says:

tournament@localhost> INSERT INTO player_event (event_id, player_id, name, url, dropped) VALUES ('98', '10206819780629227', 'Jeffrey Hemphill', 'https://www.facebook.com/app_scoped_user_id/10206819780629227/', FALSE);
ERROR 1062 (23000): Duplicate entry '98-10206819780629227' for key 'event_id'

**Comment by bakert** [comment]
I managed to repro on local. But running the rejected SQL against the DB worked fine. So ... something not entirely simple going on.
